image: node:lts-alpine

variables:
  PNPM_VERSION: "6.14.2" # Change this to the version of pnpm you want to use

before_script:
  - apk add --no-cache git pnpm
  - rm -rf ~/.pnpm-store

build:
  stage: build
  script:
    - pnpm install
    - pnpm run build

deploy:
  stage: deploy
  script:
    - apk add --no-cache git
    - pnpm install
    - pnpm run deploy

