image: node:16

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - npm install
    - npm run generate

deploy:
  stage: deploy
  script:
    - echo 'deploying to pages'
    - ls $CI_PROJECT_DIR/.output/public
  artifacts:
    paths:
      - $CI_PROJECT_DIR/.output/public
  only:
    - alpine-new

