image: node:16

stages:
  - build
  - deploy
  - pages

before_script:
  - npm install

build:
  stage: build
  script:
    - npm run build

deploy:
  stage: deploy
  when: manual
  script:
    - npm run generate
  artifacts:
    paths:
      - public
  only:
    - alpine-new

pages:
  stage: deploy
  script:
    - echo 'Deploying to GitLab Pages...'
  artifacts:
    paths:
      - public
  only:
    - alpine-new

