image: node:latest

before_script:
  - npm install
  - npm install -g pnpm

stages:
  - build
  - pages

build:
  stage: build
  script:
    - pnpm build

cache:
  key:
    files: 
      - pnpm-lock.yaml
  paths:
      - node_modules/

pages:
  stage: pages
  script:
    - pnpm generate
    - mv .output/public public
  artifacts:
    paths:
      - public
  only:
    - alpine-new

