image: node

before_script:
  - npm install

cache:
  paths:
    - node_modules/

pages:
  script:
    - npm run generate
    - cp -r .output/public/* public
  artifacts:
    paths:
      - public
  only:
    - alpine-new

