image: node:16

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - npm install
    - npm run generate

deploy:
  stage: deploy
  script:
    - npm install
    - npm run generate
  artifacts:
    paths:
      - .output/public
  only:
    - alpine-new

