image: node:lts-alpine

variables:
  PNPM_VERSION: "6.14.2" # Change this to the version of pnpm you want to use

before_script:
  - apk add --no-cache git nodejs npm 
  - npm install -g pnpm
  - rm -rf ~/.pnpm-store

build:
  stage: build
  script:
<<<<<<< HEAD
    - pnpm install
    - pnpm build

deploy:
  stage: deploy
  script:
    - apk add --no-cache git
    - pnpm install
    - pnpm build 
=======
    - npm run generate
    - cp -r .output/public/* public
  artifacts:
    paths:
      - public
  only:
    - alpine-new
>>>>>>> alpine-new

