image: node:16

stages:
  - build
  - deploy
  - pages

before_script:
  - npm install

build:
  stage: build
  script:
    - npm run build

deploy:
  stage: deploy
  when: manual
  script:
    - npm run generate
  artifacts:
    paths:
      - public
  only:
    - alpine-new

pages:
  stage: pages
  script:
    - npm install -g gitlab-ci-pages
    - gitlab-ci-pages -r gitlab.com -t $CI_BUILD_TOKEN -b main -s public -D $CI_PROJECT_NAMESPACE.gitlab.io -B gh-pages
  artifacts:
    paths:
      - public
  only:
    - alpine-new

