image: node:latest

before_script:
  - npm install

stages:
  - build
  - pages

build:
  stage: build
  script:
    - npm run build

cache:
  key:
    files: 
      - pnpm-lock.yaml
  paths:
      - node_modules/

deploy:
  stage: deploy
  when: manual
  script:
    - npm run generate
  artifacts:
    paths:
      - public
  only:
    - alpine-new

pages:
  stage: pages
  script:
    - npm run generate
  artifacts:
    paths:
      - public
  only:
    - alpine-new

